server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
# By default, routing to services will work like this:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/**
