server:
  port: 8083

spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://mongo:27017/e-commerce-platform-order-service

  graphql:
    graphiql:
      enabled: true

  rabbitmq:
    host: rabbitmq
    topicExchange: e-commerce-platform-order-service-exchange
    queues:
      order-create: order.create.queue
      order-update: order.update.queue
      order-change-status: order.change-status.queue
      order-delete: order.delete.queue
