server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/e-commerce-platform-user-service
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/e-commerce-platform
