server:
  port: 8086
  #  url: ${spring.application.name}:${server.port}
  url: http://localhost:${server.port}

spring:
  application:
    name: frontend-service

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          keycloak-web:
            client-id: ${spring.application.name}
            client-secret: 2RxH0f65UDNTflahILc9mW1c3KQmnqe8
            scope: openid, profile
            authorization-grant-type: authorization_code
          keycloak-user-service:
            client-id: ${user-service.name}
            client-secret: SlDu0pPghNiAJ2zo4UzHsp7zy1DVUvbp
            authorization-grant-type: client_credentials
            provider: keycloak
          keycloak-product-service:
            client-id: ${product-service.name}
            client-secret: sWdHyl6nx6kKw2WkM6jIf66z2nmgEpos
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
          keycloak-web:
            issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
            user-name-attribute: preferred_username

  rabbitmq:
    host: rabbitmq
    topicExchange: e-commerce-platform-order-service-exchange
    queues:
      order-create: order.create.queue
      order-update: order.update.queue
      order-change-status: order.change-status.queue
      order-delete: order.delete.queue

  kafka:
    bootstrap-servers: kafka:9092
    notifications-topic: "notifications-topic"

keycloak:
  server-url: http://keycloak:8080
  realm: e-commerce-platform
  web-registration-name: "keycloak-web" # taken from "security.oauth2.client.registration.<>"

dummy-repositories:
  pre-fill-with-dummy-data: false

user-service:
  enabled: true
  name: user-service
  url: http://api-gateway:8765/user-service/api/v1/users

product-service:
  enabled: false
  name: product-service
  url: http://api-gateway:8765/product-service/api/v1/products

order-service:
  enabled: false
  graphql-url: http://api-gateway:8765/order-service/graphql

review-service:
  enabled: false
  grpc:
    host: review-service
    port: 9090

notification-service:
  enabled: false
